export enum RouteNames {
  HOME = "HOME",
  PERSON = "PERSON",
  EDIT_PERSON = "EDIT_PERSON",
  CREATE_PERSON = "CREATE_PERSON",
  SETTINGS = "SETTINGS",
  PAGINATION = "PAGINATION",
  GAMES = "GAMES",
  PERSON_LIST = "PERSON_LIST"
}
